CONSTANTS = {
    'NUM_ENVS'                          :   8,
    'NUM_SKILLS'                        :   22,
    'STATE_SIZE'                        :   22,
    'ACTION_SIZE'                       :   43,
    "TARGET_P_KNOW"                     :   0.97,
    'NUM_OBS'                           :   '100',
    'VILLAGE'                           :   '130',
    'STUDENT_ID'                        :   'new_student',
    'STUDENT_MODEL_NAME'                :   'hotDINA_skill',
    'AREA_ROTATION'                     :   'L-N-L-S',
    'START_POS'                         :   '0,0',
    'AVG_OVER_RUNS'                     :   50,
    'AGENT_TYPE'                        :   None,
    'AREA_ROTATION_CONSTRAINT'          :   True,
    'TRANSITION_CONSTRAINT'             :   True,
    "LEARNING_RATE"                     :   5e-4,
    "FC1_DIMS"                          :   1024,
    "FC2_DIMS"                          :   2048,
    'FC3_DIMS'                          :   1024,
    'PPO_STEPS'                         :   64, # Must be a multiple of MINI_BATCH_SIZE
    'PPO_EPOCHS'                        :   10,
    'TEST_EPOCHS'                       :   5,
    'NUM_TESTS'                         :   10,
    'GAE_LAMBDA'                        :   0.95,
    "MINI_BATCH_SIZE"                   :   32,
    "MAX_TIMESTEPS"                     :   200,
    'GAMMA'                             :   0.99,
    'GAE_LAMBDA'                        :   0.95,
    'PPO_EPSILON'                       :   0.2,
    "CRITIC_DISCOUNT"                   :   0.5, 
    "ENTROPY_BETA"                      :   0.001,
    "RUN_NUM"                           :   0,
    'PRINT_STUDENT_PARAMS'              :   True,
    'CLEAR_LOGS'                        :   True,
    # Current RoboTutor Thresholds
    'LOW_PERFORMANCE_THRESHOLD'         :   0.5,
    'MID_PERFORMANCE_THRESHOLD'         :   0.83,
    'HIGH_PERFORMANCE_THRESHOLD'        :   0.9,
    'LOW_LENIENT_PERFORMANCE_THRESHOLD' :   0.4,
    'MID_LENIENT_PERFORMANCE_THRESHOLD' :   0.55,
    'HIGH_LENIENT_PERFORMANCE_THRESHOLD':   0.7,
}